# Generated by Django 5.1.6 on 2025-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(help_text='Comma-separated list of technologies used'),
        ),
    ]
